service: my-first-sls-service
app: my-first-sls-app
org: hamanovich

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  iam:
    role:
      statements:
        - ${file(iam/usersTableIAM.yml):usersTableIAM}

resources:
  Resources:
    usersTable: ${file(resources/usersTable.yml):usersTable}

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - http:
          path: hello
          method: get

  createUser:
    handler: src/handlers/createUser.handler
    description: create user handler
    events:
      - http:
          path: user
          method: post
