service: my-first-sls-service
app: my-first-sls-app
org: hamanovich

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  environment:
    USERS_TABLE_NAME: ${self:custom.usersTable.name}
  iam:
    role:
      statements:
        - ${file(iam/usersTableIAM.yml):usersTableIAM}

resources:
  Resources:
    usersTable: ${file(resources/usersTable.yml):usersTable}

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - http:
          path: /hello
          method: GET

  createUser:
    handler: src/handlers/createUser.handler
    description: create user handler
    events:
      - http:
          path: /user
          method: POST

  getUsers:
    handler: src/handlers/getUsers.handler
    description: get all users
    events:
      - http:
          path: /users
          method: GET

  getUser:
    handler: src/handlers/getUser.handler
    description: get one user
    events:
      - http:
          path: /user/{id}
          method: GET

custom:
  usersTable:
    name: !Ref usersTable
    arn: !GetAtt usersTable.Arn